version: '1.0'

services:
  postgres:
    container_name: postgres

    image: postgres:12
    env_file:
      - server/.env
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: tasker
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 6432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: